steps:
# Build backend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/levi-backend:latest', './backend']

# Push backend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/levi-backend:latest']

# Deploy backend to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'levi-backend', '--image', 'gcr.io/$PROJECT_ID/levi-backend:latest', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated', '--port', '8080']

# Build frontend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/levi-frontend:latest', './frontend']

# Push frontend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/levi-frontend:latest']

# Deploy frontend to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'levi-frontend', '--image', 'gcr.io/$PROJECT_ID/levi-frontend:latest', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated', '--port', '8501']
